kind: Pod
apiVersion: v1
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  containers:
    - name: http-server
      image: lmagana92/http-server
      imagePullPolicy: Always
      env:
        - name: PORT
          value: "8080"